### ISSUE TITLE
Multiplus Detailed Info

### ISSUE THREAD

**Issue by kittyorianda** [kwindrem/GuiMods#116]
Would it be possible that instead of the time on the Multiplus 2 (Inverter) the ampere consumption would be displayed? 

The time I do not see now as so important on the screen.
![Screenshot 2023-02-09 002518](https://user-images.githubusercontent.com/106024534/217675811-e1a9ba8d-35c6-4644-9a6a-57d1b75f5ba2.jpg)

**Comment by kwindrem** [comment]
Amp-hours consumed really belongs in the battery tile. As you can see, it's full with what's there.

If you have the ability to edit the qml code, anything is possible.

**Comment by kittyorianda** [comment]
It is not intended to display the amperes consumed. That really belongs to the battery, I agree. My Multiplus converts the 12V current to 230V and I want to know how many amps this inverter is consuming and I want it to show that on its tile. On details page it shows me that with "DC Power / Current consuming".

**Comment by kwindrem** [comment]
I'll admit that the lack of information on the Inverter tile is inconsistent with the rest of the system as displayed on this page. Singing out one parameter of interest is likely to differ with each individual: you want DC current, someone else may want AC power.
The gauge displayed in the inverter tile does provide a relative indication of the AC power consumed or supplied by the inverter, just not a numerical value. I see a graphical relative indication as more important to a numerical value since one needs to read the value the mentally compare it to a known (or possibly unknown) maximum.
In your simple system the DC power and current will be close to the AC Output power as you can see from the Inverter detail you provided.
I am reluctant to make any changes in this area at this time.
