### ISSUE TITLE
GuiMods v7.16 incompatible with Venus OS v3.00~17 ?

### ISSUE THREAD

**Issue by sergios100** [kwindrem/GuiMods#119]
Hi!
I just updated to Venus OS v3.00~17 on my raspberry PI 4 and it seems that GuiMods v7.16 is not working anymore.
<img width="507" alt="Bildschirm­foto 2023-02-17 um 23 35 08" src="https://user-images.githubusercontent.com/63123058/219808989-91b49132-da05-4a74-985d-ad1927b6f723.png">

Is this a known issue or am I doing someting wrong?

Thanks a lot!

Cheers!

**Comment by kwindrem** [comment]
v7.16 should support v3.00~17 so I'm not sure what is going on. It's working here.

Use PackageManager to do a Settings backup to removable media and post the logs.zip file here and I'll take a look.

**Comment by sergios100** [comment]
I will do that!
Thanks!

**Comment by sergios100** [comment]
Please find the requested Zip-File here:
[logs.zip](https://github.com/kwindrem/GuiMods/files/10772398/logs.zip)

Cheers! Sergio

**Comment by kwindrem** [comment]
The install is failing because compatible versions for two files can't be found. I've checked and the v3.00~17 file set includes files that ARE a match for those files in the v3.00~17 release. This usually means something modified the files before the GuiMods setup script runs. The easiest way to recover is to revert to a previous version firmware using Stored firmware, then reinstall the v3.00~17 using online updates. If that fails, try redownloading GuiMods.

**Comment by gainestr** [comment]
You may want to enable “Auto install packages” for this update.  Worked fine for me.

**Comment by sergios100** [comment]
Hi everyone,

got it to run finally! don't know how exactly, but in the process I **removed the GuiMod package**, "**Initalized the Package Manager**", **enabled "Auto install packages"** set **"Automatic GitHub downloads"** to **"on"**.
After a few seconds the Remote Console went offline, and when it came back, GuiMods and all the other Packages are up and running as before. I did not have to revert to a previous firmware in the process.

So thanks a lot for your support! The Issue is solved for me!

Cheers Sergio
