### ISSUE TITLE
It would be fine to have the posibility to show the Pv inverter seperatly and not in sum

### ISSUE THREAD

**Issue by Ichbinwerichbin** [kwindrem/GuiMods#181]
Hi Kwindrem
If i habe no PV charger activated i can see the PV inverter as two rows each showing me the input it delivers. With PV charger activated i cant. He shows me only the sum of both. Also i dont understand why the PV inverters are bound to the multi as they are AC side coupled. I have AC out deactivated and only ACin active. So the PV inverters  should show it bound to the grid. Victron Image did this yours not. What is the reason
![grafik](https://github.com/kwindrem/GuiMods/assets/142200637/ca9a7501-8d80-4218-9ad1-ed5ad1d35181)
 
![grafik](https://github.com/kwindrem/GuiMods/assets/142200637/3f11c37c-f004-4535-a89a-0f355da838ed)

I do not really need the display of  L1L2L3 in the load tile. So if there where a posibility to enhance the PV inverter to show both or more and dont show the L1L2L3 to have the place to show it, or put the pv charger under the victron tile i would be really happy.
If i can make that myself and i hadnt found it, then pls help me to set it correct.
Thanks a lot i like this overview much more then the victron one.
Stefan

**Comment by kwindrem** [comment]
The GuiMods simple flow overview is based on the one created by Victron. The PV inverter connection to the Multi is obviously wrong but I assume was done to avoid cluttering the display with crossed flow lines.

I'm not sure what the problem is with the PV Charger showing up if you don't have a PV Charger in your system. If you do have a PV Charger then unfortunately there is no room to display individual PV inverter details. To complicate things, this overview combines AC in and AC out in a single tile that is shown top right.

What you are probably seeing in the Victron overview is the "Grid Parallel" overview which shows PV inverters on both the input and output side of the Multi. Both of your PV inverters would probably show up on the input side since that is where they are located. But still, you would only see the total power for both. The GuiMods AC Coupled overview does provide separate AC in and AC out tiles and proper flow connections. However these lack the individual leg info and also individual PV inverter contributions. But you might look at that as an option for you.

Yes, there are many configurations that would benefit from rearranging tiles when other components don't exist. Customizing the flow overview for each scenario would be a full time job for me as each installation has different needs.

If you are interested in modifying the code for yourself, the files of concern are OverviewHubEnhanced.qml for the page you are currently using and Overview FlowComplex.qml for the AC and DC coupled versions. Most tiles are created with an OverviewBox object. Flow lines are created with OverviewConnection objects. Each segment of a line requires it's own OverviewConnection with power calculated based on the flow in/out of each end of the line.
