### ISSUE TITLE
White screen on GUI after upgrading to Venus OS 3.31

### ISSUE THREAD

**Issue by lfhoward** [kwindrem/GuiMods#248]
Hi Kevin,

I foolishly updated my Venus OS today after 3.31 was just released. Victron did something to the GUI that caused GUI Mods to display a white screen. I am not able to revert to the previous version of the OS because I can't access the settings anymore. I do not have the ability to SSH into the machine because the new version resets my password, but the GX device is online and reporting data to the VRM.

You'll notice a new GUI-v2 Beta menu option in the VRM Portal now. It gives me an error and doesn't work. (Error loading the WebAssembly)
![Screenshot 2024-04-22 at 12 17 52 PM](https://github.com/kwindrem/GuiMods/assets/99151873/4c87f872-224f-4d56-a025-b8815c66206b)

Remote Console now looks like this:
![Screenshot 2024-04-22 at 12 18 46 PM](https://github.com/kwindrem/GuiMods/assets/99151873/4ff43bff-9558-444a-bd2c-666a5d5af990)

I figure you're already on it, but since there was not an issue about  v3.31 posted yet, I thought I'd start that so others who are upgrading can find it.

Best,
Lauren

**Comment by drtinaz** [comment]
As long as you have auto downloads and auto installs enabled in package manager all should be back to normal once Kevin releases a fix.

**Comment by kwindrem** [comment]
I'm not experiencing a white screen with v3.31 on my test system (a RPI 4) or my Cerbo in my RV with GuiMods v10.20 and SetupHelper v7.18. Your issue might be due to another package.

if you have ssh capability you can manually uninstall GuiMods:

/data/GuiMods/setup uninstall auto

Same with other packages

or check the gui log to see what's causing the white screen:

tail -50 /data/log/gui/current | tai64nlocal

I will release a new version of GuiMods shortly with file sets for v3.31 but doubt that will change anything.

**Comment by kwindrem** [comment]
GuiMods v10.21 with a v3.31 file set has been released

BTW, v3.31 does not include gui-v2 so that explains why the link in VRM does not work. If you still have a v3.40~x in backup firmware you can revert back to that but make sure automatic firmware updates is turned off first.

**Comment by lfhoward** [comment]
Unfortunately I do not have ssh capability because when upgrading to a new Venus OS version I always have to reset my password first in settings to be able to use ssh. That means I can't check the log or uninstall anything manually until I get the GUI back.

The GUI screen is still white. I wonder if I had a bad OS install.

I have an older image/version (v3.2x I think) of my Victron system on another SD Card. I will try swapping the SD card over and hopefully it will give me back access to my system. 

Any other ideas before I try that? Is it possible to uninstall GuiMods via USB?

**Comment by kwindrem** [comment]
I'm assuming you have rebooted the GX device. If not, you should try that next.

Since you are on a RPI, you can remove the SD card and look at the logs from another system but it needs to be able to read ext file systems. They are in /data/log which is one of 4 partitions on the SD card.

Yes there is a way to uninstall all packages. SetupHelper includes a blind uninstall mechanism. It's expalained in the ReadMe. That mechanism also allows a firmware update if you put the appropriate .swu file on the same flash drive with the blind uninstall venus-data.tgz file.

Also look into setting up SSH keys for your GX devices. That sidesteps the need to reset the password when updating the firmware.
