### ISSUE TITLE
PV Charger Detail is empty after installing v5.23

### ISSUE THREAD

**Issue by t440142** [kwindrem/GuiMods#57]
![grafik](https://user-images.githubusercontent.com/100781508/166911651-3dc82ad9-6d3a-459e-b830-1d780564c392.png)
![grafik](https://user-images.githubusercontent.com/100781508/166911808-9808f131-d050-49ac-b515-a68985ccacd4.png)
Hi,

Can you have a look at this?

Thanks

Best regards
Peter

Firmware
PV Charger: 1.59
Cerbo GX: 2.84
SetupHelper: 4.13
GuiMods: 5.23

**Comment by kwindrem** [comment]
I'm not sure what is going on because the same mechanism I use to discover PV chargers in the overview is also used in the detail.

Have you rebooted the GX device?

Did this issue show up recently or has it always been like this?

Logs would help. In this case it would be the gui log. SetupHelper v4.13 adds a log collection mechanism in the PackageManager backup/restore settings.
Do the backup then remove the media. Plugging the media in a computer you'll see a logs folder. Zip that up and post it here.

**Comment by t440142** [comment]
Hi,

V5.20 works as expected, all informations are displayed.
V5.22 cannot be installed, the error message is "GuiMods fileset incomplete".
Then I tried v5.33 again, the detail display is again incomplete as shown in the screenshot.

I will try to establish an ssh connection to access log files. Have to read how to set it up.

Best regards
Peter

**Comment by kwindrem** [comment]
I have reproduced the problem and will get a fix posted today. Thanks for reporting.

**Comment by kwindrem** [comment]
Should be fixed now in v5.24

The problem was I had included code to handle PV chargers with multiple MPPT trackers. That code has yet to be tested but got accidentally merged into the main branch when I added support for v2.90~3. It's still in place but I have tested it with a single PV charger with a single tracker.

**Comment by t440142** [comment]
Everything works as expected again, thanks for your support.
